# SPDX-FileCopyrightText: 2024 University of Washington
#
# SPDX-License-Identifier: CC0-1.0

version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py