name: Publish App

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/cutview/
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Build
        run: |
          python -m poetry version ${{ github.event.release.tag_name }}
          python -m poetry build
      - name: Publish to Pypi
        uses: pypa/gh-action-pypi-publish@release/v1