name: Publish App

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/nccut/
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m poetry self add poetry-bumpversion
      - name: Build
        run: |
          python -m poetry version ${{ github.event.release.tag_name }}
          python -m poetry build
      - name: Commit Version Updates
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Pypi
        uses: pypa/gh-action-pypi-publish@release/v1

  docs:
    runs-on: ubuntu-latest
    needs: pypi
    steps:
      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
