 # This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install X11
      run: |
        sudo apt-get update 
        sudo apt-get install xorg
        sudo apt-get install xorg openbox
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Install dependencies
      run: |
        cd cutview
        python -m poetry install
    - name: Lint with flake8
      run: |
        cd cutview
        python -m poetry run python -m flake8 --ignore=E402,E501
    - name: Test with unittest
      run: |
        cd cutview
        python -m poetry run python -m pytest
        
  windows_test:
    runs-on: windows-latest

    env:
      KIVY_GL_BACKEND: 'angle_sdl2'
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Install dependencies
      run: |
        cd cutview
        python -m poetry install
    - name: Lint with flake8
      run: |
        cd cutview
        python -m poetry run python -m flake8 --ignore=E402,E501
    - name: Test with unittest
      run: |
        cd cutview
        python -m poetry run python -m pytest

  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: cutview/paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf
