name: Python application

on:
  push:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version }}
    - name: Install X11
      run: |
        sudo apt-get update 
        sudo apt-get install xorg
        sudo apt-get install xorg openbox
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Install dependencies
      run: |
        python -m poetry install --with test
    - name: Lint with flake8
      run: |
        python -m poetry run python -m flake8 --ignore=E402,E501
    - name: Test with unittest
      run: |
        python -m poetry run python -m pytest -s
        
  windows_test:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [ "3.9", "3.10", "3.11", "3.12" ]
    env:
      KIVY_GL_BACKEND: 'angle_sdl2'
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version }}
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Install dependencies
      run: |
        python -m poetry install --with test
    - name: Lint with flake8
      run: |
        python -m poetry run python -m flake8 --ignore=E402,E501
    - name: Test with unittest
      run: |
        python -m poetry run python -m pytest

  paper:
      runs-on: ubuntu-latest
      name: Paper Draft
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Build draft PDF
          uses: openjournals/openjournals-draft-action@master
          with:
            journal: joss
            paper-path: paper.md
        - name: Upload
          uses: actions/upload-artifact@v4
          with:
            name: paper
            path: paper.pdf
        - name: Version Test
          run: |
            echo ${{{ github.ref_name }}:1}
